[package]
name = "agtrace-index"
version.workspace = true
edition.workspace = true
description = "SQLite index for agtrace"
license.workspace = true

[dependencies]
agtrace-types.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
rusqlite.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
